column_map = {
 'fecha_dato':'partition',
 'ncodpers':'customer_id',
 'ind_empleado':'employee_idx',
 'pais_residencia':'country_residence',
 'sexo':'sex',
 'age':'age',
 'fecha_alta':'member_since',
 'ind_nuevo':'new_customer', # register within 6 months
 'antiguedad':'seniority',   # in month
 'indrel':'primary',
 'ult_fec_cli_1t':'last_date_primary',
 'indrel_1mes':'type',
 'tiprel_1mes':'relation_type',
 'indresi':'residence_idx',
 'indext':'foreigner_idx',
 'conyuemp':'spouse_idx',
 'canal_entrada':'channel',
 'indfall':'deceased_idx',
 'tipodom':'address_type',
 'cod_prov':'province_code',
 'nomprov':'province_name',
 'ind_actividad_cliente':'activity_idx',
 'renta':'gross_income_household',
 'segmento':'segmentation',
 'ind_ahor_fin_ult1':'prod_saving_account',
 'ind_aval_fin_ult1':'prod_guarantees',
 'ind_cco_fin_ult1': 'prod_current_account',
 'ind_cder_fin_ult1':'prod_derivada_account',
 'ind_cno_fin_ult1': 'prod_payroll_account',
 'ind_ctju_fin_ult1':'prod_junior_account',
 'ind_ctma_fin_ult1':'prod_mas_particular_account',
 'ind_ctop_fin_ult1':'prod_particular_account',
 'ind_ctpp_fin_ult1':'prod_particular_plus_account',
 'ind_deco_fin_ult1':'prod_short_term_deposit',
 'ind_deme_fin_ult1':'prod_medium_term_deposit',
 'ind_dela_fin_ult1':'prod_long_term_deposit',
 'ind_ecue_fin_ult1':'prod_e_account',
 'ind_fond_fin_ult1':'prod_funds',
 'ind_hip_fin_ult1': 'prod_mortgage',
 'ind_plan_fin_ult1':'prod_pensions',
 'ind_pres_fin_ult1':'prod_loans',
 'ind_reca_fin_ult1':'prod_taxes',
 'ind_tjcr_fin_ult1':'prod_credit_card',
 'ind_valo_fin_ult1':'prod_securities',
 'ind_viv_fin_ult1': 'prod_home_account',
 'ind_nomina_ult1':  'prod_payroll',
 'ind_nom_pens_ult1':'prod_payroll_pensions',
 'ind_recibo_ult1':  'prod_debit'
}